### ISSUE TITLE
boot2docker.console

### ISSUE THREAD

**Issue by colby-swandale** [aredridel/xhyvedocker#2]
The script is mentioning "boot2docker.console" a number of times but i cannot find a mention of it anywhere. Is this something boot2docker installs, could you elaborate more? Thanks.

**Comment by aredridel** [comment]
It's a socket file created by dtach. (Think of it only as the attach/detach functions of screen or tmux.)

**Comment by colby-swandale** [comment]
Ah yes, i should have read the dtach man pages before raising an issue. Thanks.
