### ISSUE TITLE
debugfs

### ISSUE THREAD

**Issue by colby-swandale** [aredridel/xhyvedocker#8]
debugfs does not appear to be installed after i run `xhyvedocker deps` and it is not shipped with OS X but there is mention of it in the bash script. Am i missing something? do i need to install something else to get debugfs?

**Comment by aredridel** [comment]
It's part of e2fsprogs -- which the script adds to the path.

**Comment by colby-swandale** [comment]
Ah, i see what happened. None of the binary files are being symlinked to `/usr/local` so unless you add the folder brew installed e2fsprogs into to your $PATH you won't be able to call it without a /path/to/debugfs..

May need to add something in documentation..

```
$ brew reinstall e2fsprogs
==> Reinstalling e2fsprogs
==> Downloading https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.42.12/e2fsprogs-1.42.12.tar.
Already downloaded: /Library/Caches/Homebrew/e2fsprogs-1.42.12.tar.gz
==> ./configure --prefix=/usr/local/Cellar/e2fsprogs/1.42.12 --disable-e2initrd-helper
==> make
==> make install
==> make install-libs
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

This brew installs several commands which override OS X-provided file system commands.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/e2fsprogs/lib
    CPPFLAGS: -I/usr/local/opt/e2fsprogs/include

==> Summary
🍺  /usr/local/Cellar/e2fsprogs/1.42.12: 134 files, 5.0M, built in 44 seconds
```

**Comment by aredridel** [comment]
It should be able to refer to it in the keg. The PATH is set at the top of the xhyvedocker script.

**Comment by colby-swandale** [comment]
Oh, how did i not see that. This is clearly a problem with my setup then. Thanks.

**Comment by aredridel** [comment]
You're welcome! It's not very smart though so if your cellar's in a weird place...
